<h1 class="text-center d-flex justify-content-between">
  <a href="/"><i class="fas fa-caret-left text-dark"></i></a>
  <span class="ml-auto">Novo questionário</span>
  <div></div>
</h1>
<hr>

<form class="m-sm-3 m-lg-5" action="/store" method="POST">
  <div class="input-group mb-3">
    <span class="input-group-text bg-primary text-white">Título</span>
    <input 
      type="text" 
      class="form-control" 
      name="quiz_title" 
      placeholder="Digite um título ..."
      maxlength="255"
      required
    >
  </div>

  <div id="question_container" class="mt-4">
    <hr>
    <h3 class="text-center mb-3">Questões</h3>

    <div id="question_1" class="input-group mb-3">
      <span class="input-group-text bg-primary text-white">Enunciado</span>
      <input 
        type="text" 
        class="form-control"
        name="quiz_questions[]" 
        placeholder="Digite o enunciado ..."
        maxlength="255"
        required
      >
    </div>
  </div>

  <div class="col-12 d-grid gap-2">
    <button 
      type="button" 
      class="btn btn-outline-primary p-2 d-flex justify-content-center align-items-center"
      id="new_question_button"
    >
      <i class="fas fa-plus"></i>
      <strong class="px-3">Nova questão</strong>
    </button>
  </div>

  <div class="col-12 d-grid gap-2">
    <hr>
    <button 
      type="submit" 
      class="btn btn-primary p-2 d-flex justify-content-center align-items-center"
    >
      <i class="fas fa-save"></i>
      <strong class="px-3">Salvar</strong>
    </button>
  </div>
</form>