<div class="row">

  <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 d-grid gap-2 mb-3">
    <a href="/create" class="btn btn-outline-info p-5 d-flex justify-content-center align-items-center">
      <i class="fas fa-plus"></i>
      <strong>Novo questionário</strong>
    </a>
  </div>

  <?php foreach($this->view->quizes as $quiz) { ?>
    <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 d-grid gap-2 mb-3">
      <a href="/show?id=<?= $quiz['id'] ?>" class="btn btn-info p-5 text-light">
        <strong>
          <?= $quiz['title'] ?>
        </strong>
        <br>
        <small>Criado: <?= date("d/m/Y", strtotime($quiz['created_at'])) ?></small>
      </a>
    </div>
  <?php } ?>

</div>